version: '3.8'

# docker run -it -p 137:137/udp -p 138:138/udp -p 139:139 -p 445:445 -p 445:445/udp --hostname 'filer' -v /media/usbdrive:/share/folder/usbdrive elswork/samba:armv7l -u "aurick:aurick" -s "usbdrive:/share/folder:rw:aurick"

services:
  samba:
    image: elswork/samba
    container_name: samba
    hostname: samba
    volumes:
#      - /media/usbdrive:/share/folder/usbdrive
      - /mnt/usb1:/share/usb1
      - /mnt/usb2:/share/usb2
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
      - 445:445/udp
    restart: always
#    command: -u "aurick:aurick" -s "usbdrive:/share/folder:rw:aurick"
    command: -u "aurick:aurick" -s "share:/share:rw:aurick"
