version: '3.7'

services:
  samba:
    build:
      context: .
      dockerfile: Dockerfile
    image: samba-docker
    container_name: samba
    hostname: samba
    volumes:
      - /media/usb1:/share/usb1
      - /media/usb2:/share/usb2
      - /media/usb3:/share/usb3
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
      - 445:445/udp
    restart: always
    command: -u "aurick:aurick" -s "share:/share:rw:aurick"
