version: '3.8'

services:
  samba:
    build:
      context: .
      dockerfile: Dockerfile
    image: samba-docker
    container_name: samba
    hostname: samba
    restart: always
    volumes:
      - /mnt/usb1:/share/usb1
      - /mnt/usb2:/share/usb2
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
      - 445:445/udp
    command: -u "aurick:aurick" -s "share:/share:rw:aurick"
    networks:
      - samba

networks:
  samba: